---
ID: "78568af1-6386-44c3-8533-00ce2fdc0835"
Parent: "1e654264-9e8d-4f3b-84bc-8e5a5e3cde13"
Template: "3505f93a-1bbd-4ea4-bfab-09f44e88a594"
Path: /sitecore/system/Settings/Analytics/Marketing Automation/Activity Types/Remove from campaign/Paths/Default
DB: master
SharedFields:
- ID: "ec7ee750-6c26-4def-aa5f-71dcd3a875de"
  Hint: Key
  Value: default
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "229cea16-4ad6-495a-aa42-0e0e05709162"
      Hint: Name
      Value: Default
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170227T125312Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7b09133e-9b7c-496a-ac2a-85f6d260bfb2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20170808T041105Z
