---
ID: "bfaa840d-0e6d-4d6a-b6c4-bf529f1ca62e"
Parent: "10e6e1a5-d6ce-4f55-9947-be8f8ea2bf8c"
Template: "854ba861-63ea-4a0c-8c7b-541e9a7ec4c1"
Path: "/sitecore/system/Settings/Rules/Definitions/Elements/XConnect - Visit Conditions/Tags/Default"
DB: master
SharedFields:
- ID: "42f77151-098f-496a-94cf-590b7edeeabe"
  Hint: Tags
  Type: Multilist
  Value: "{8A4C313D-2BBD-4CF2-AB65-4E059AA06F06}"
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{6F0688E4-7B16-482F-845B-35836FD15D14}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170216T133739Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d911508c-b9d8-49b7-8a9b-82edd2734c01"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20170217T102959Z
