---
ID: "f0c519ae-be32-4722-bcb1-e9e1449861e7"
Parent: "3f0d79a3-62de-4c9c-9c44-66e3e73ab9cd"
Template: "6e188261-e572-4330-b88a-88c68b0926e7"
Path: /sitecore/templates/Branches/Feature/Experience Accelerator/Search/SearchDataFolder/$name/Checklist Filter/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190514T113542Z
    - ID: "ae2fb54e-10cb-4dec-bf62-dfeb17d3cc7e"
      Hint: Title
      Value: Sxa Tags
