---
ID: "10484d98-367f-4aea-a150-405726b5049a"
Parent: "7bfc37a7-7817-48a4-afea-b4c1c631b93a"
Template: "dd22f1b3-bd87-4db2-9e7d-f7a496888d43"
Path: "/sitecore/system/Modules/PowerShell/Script Library/SXA/SXA - Scaffolding/Content Editor/Insert Item/Site"
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/flag_generic.png
- ID: "1c76313e-3c8c-4807-a826-135d10c39299"
  Hint: ShowRule
  Type: Rules
  Value: |
    <ruleset>
      <rule
        uid="{4ACD3B3E-3AB3-48A5-AA23-A21A5568AE18}">
        <conditions>
          <condition
            id="{5DE6D53E-EA62-4D17-8BDD-FEBCD80AC07B}"
            uid="B605EC773DE84B18B6E05E668A6C88F2"
            templateid="{C0CBBC66-4EF0-4660-A0D3-91E862FCCB65}" />
        </conditions>
      </rule>
      <rule
        uid="{CE3CA85A-BA9F-4059-AE21-93893949BDC9}">
        <conditions>
          <condition
            id="{5DE6D53E-EA62-4D17-8BDD-FEBCD80AC07B}"
            uid="FC60C03DE9C5479CB43DA7ABC03496BC"
            templateid="{215F8C54-68B3-4481-A20B-A5716F06081F}" />
        </conditions>
      </rule>
    </ruleset>
- ID: "b1a94ff0-6897-47c0-9c51-aa6acb80b1f0"
  Hint: Script
  Value: |
    Import-Function Validate-PowerShell
    
    Test-PowerShell
    
    Try
    {
        $ctx = gi .
        Import-Function New-Site
        
        $model = Show-NewSiteDialog $ctx
        New-Site $model
    }
    Catch
    {
        $ErrorRecord=$Error[0]
        Write-Log -Log Error $ErrorRecord
        Show-Alert "Something went wrong. See SPE logs for more details."
        Close-Window
    }
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160704T134330Z
