---
ID: "e2fec873-09a1-4c5c-a389-946d6ca567d1"
Parent: "8f6324bf-c331-4ff4-af3f-d3b3f6578903"
Template: "b2613cc1-a748-46a3-a0db-3774574bd339"
Path: /sitecore/templates/Branches/Foundation/Experience Accelerator/Local Datasources/Datasource Configuration
DB: master
BranchID: "f6b0e6f1-2451-4c72-94fd-22d7b93b592a"
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/signpost3.png
- ID: "854cc8f6-94ad-4521-a4b6-44ed8f794c98"
  Hint: Command
  Value: "datasourceresolution:createdatasourcesetting(parentID=$ParentID)"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160504T145721Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
