---
ID: "5df9b10f-f5b5-4e6a-ad58-08125a701147"
Parent: "0fe895a2-63b1-470f-93f4-a166849b13f6"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/templates/Branches/Feature/Experience Accelerator/Page Content/Default Promo Variant/$name/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160427T134629Z
