---
ID: "8b1771e7-2a9a-445f-b6b2-4783a1a0c8d8"
Parent: "d69b80b0-7203-4efe-803a-2b75a2c21a01"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/layout/Placeholder Settings/Feature/Experience Accelerator/Security
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 600
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160610T094220Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
