---
ID: "48ae7c0a-5219-4269-b9e6-1b41beb52164"
Parent: "f5ffab16-5e15-448f-a4b9-70b39066d409"
Template: "0437fee2-44c9-46a6-abe9-28858d9fee8c"
Path: /sitecore/templates/Foundation/Experience Accelerator/Json Variants/Base
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: "-100"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170526T063618Z
