---
ID: "85c410ad-ccba-4064-a547-35b57c07b9e7"
Parent: "3b47c187-7f80-497f-95d9-16d072e3e6bd"
Template: "dd22f1b3-bd87-4db2-9e7d-f7a496888d43"
Path: "/sitecore/system/Modules/PowerShell/Script Library/SXA/SXA - Security/Functions/Set-SxaSecurity"
DB: master
SharedFields:
- ID: "b1a94ff0-6897-47c0-9c51-aa6acb80b1f0"
  Hint: Script
  Value: |
    Import-Function Add-RoleMembers
    Import-Function Add-Role
    Import-Function Add-Roles
    Import-Function Get-RoleObjects
    Import-Function Test-AllRolesExist
    
    function Set-SxaSecurity {
        [CmdletBinding()]
        param()
    
        begin {
            Write-Verbose "Cmdlet Set-SxaSecurity - Begin"
        }
    
        process {
            Write-Verbose "Cmdlet Set-SxaSecurity - Process"
            $defaultDomainName = "SXA"
            $sxaDomain = Get-Domain -Name $defaultDomainName -ErrorAction SilentlyContinue
            if (-not $sxaDomain) {
                Write-Verbose "Domain not found"
    
                Write-Verbose "Creating '$defaultDomainName' domain"
                New-Domain -Name $defaultDomainName > $null
            }
            
            $roleItems = Get-ChildItem -Path "/sitecore/system/Settings/Feature/Experience Accelerator/Security/Security Setup/SXA"
            $roleItems = Get-RoleObjects $roleItems
            
            $pendingRoles = @()
            $roleItems | % {
                $currentRole = $_
                Write-Verbose "Validating role: $($currentRole.RoleName)"
                if (-not(Test-AllRolesExist $currentRole)) {
                    Write-Verbose "Creating '$defaultDomainName' roles"
                    Add-Roles $currentRole
                    $pendingRoles += $currentRole
                }
            }
            $pendingRoles | % {
                $currentRole = $_
                Write-Verbose "Assigning inheritance for $($currentRole.RoleName)"
                Add-RoleMembers $currentRole
            }
    
        }
    
        end {
            Write-Verbose "Cmdlet Set-SxaSecurity - End"
        }
    }
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170405T095838Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
