---
ID: "c5678f86-d23d-41ca-b236-a1989fcfdac7"
Parent: "9dd054c0-fb16-420d-a4cf-d15d7223e032"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/templates/Branches/Feature/Experience Accelerator/Navigation/Default Link List Variant/$name/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160516T081519Z
