---
ID: "a7d1fc3e-78fc-4ff9-8989-a229111c5f71"
Parent: "61a9df06-dd99-4f24-9dd9-9f75f50449db"
Template: "0a92feee-0e15-4e81-b044-2ad901b88ddd"
Path: /sitecore/system/Settings/Foundation/Experience Accelerator/Multisite/Enums/Site Link Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160630T083105Z
