---
ID: "0a8a57a5-9a52-4cbd-8315-43192c9305ea"
Parent: "c4354a50-7a46-4df0-89ab-dd02db6d15cb"
Template: "c4354a50-7a46-4df0-89ab-dd02db6d15cb"
Path: /sitecore/templates/Feature/Experience Accelerator/Search/Datasource/Page Selector/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140818T162024
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "6e8ae3cb-eafc-49a1-a1f2-efe2e9b04acd"
      Hint: PreviousLabel
      Value: Previous
    - ID: "85c8ab08-22ca-41bf-9673-f7d1f25174a7"
      Hint: NextLabel
      Value: Next
    - ID: "c431b494-cbb5-4bbd-8276-3d9be420fc92"
      Hint: LastLabel
      Value: Last
    - ID: "cd2000f5-5ad5-44f0-8c83-5a87ea9812ac"
      Hint: FirstLabel
      Value: First
