---
ID: "e5d1fc54-131e-4882-b309-677ba02ea3fb"
Parent: "efac8e1b-de06-41f5-aa98-61f1745128d5"
Template: "efac8e1b-de06-41f5-aa98-61f1745128d5"
Path: /sitecore/templates/Feature/Experience Accelerator/Navigation/Rendering Parameters/Archive/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150930T105750Z
