---
ID: "a5aa6bfe-5feb-4234-b083-517666d02cc9"
Parent: "c4658673-5d70-44ed-9004-d66eac1dc718"
Template: "3aea335c-d06d-45b1-841a-cbc8d2d1ce40"
Path: /sitecore/system/Settings/Foundation/JSS Experience Accelerator/PlaceholderSettings/Placeholder Settings Site Setup/Add Placeholder Settings Folder
DB: master
SharedFields:
- ID: "52c91c75-6698-4701-a8a2-242ace59a8d6"
  Hint: Location
  Type: Treelist
  Value: "{BE311027-A473-4A08-91B6-4F183EFF040E}"
- ID: "7868e6bc-525c-4fce-ab8a-77da3e09b171"
  Hint: Name
  Value: Placeholder Settings
- ID: "e62c28f0-9d3b-46e2-8bec-a5e120542499"
  Hint: Template
  Type: Treelist
  Value: "{52288E39-7830-4694-B62D-32A54C6EF7BA}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190121T093800Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
