---
ID: "a25d9340-a35f-4518-93d5-a1947321de60"
Parent: "1e73f539-0a2d-4bdc-a7ae-65b223c0db0a"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Foundation/Experience Accelerator/Placeholder Settings/Base/_Base Placeholder Settings Folder/Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191007T180511Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
