---
ID: "1a2ccae9-578f-4603-9a0c-8f259f3a756b"
Parent: "83754cb5-0447-4022-906d-bb36718ad183"
Template: "83754cb5-0447-4022-906d-bb36718ad183"
Path: /sitecore/system/Settings/Foundation/Experience Accelerator/Local Datasources/Virtual Page/__Standard Values
DB: master
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Page
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160718T090743Z
