---
ID: "32359a5e-2456-4248-88ce-f3dcfabb1ff3"
Parent: "023d72d7-9e9b-464f-96ce-29441ef3c542"
Template: "292ccfcd-7790-4692-856b-76014b8038e7"
Path: /sitecore/system/Settings/Foundation/Experience Accelerator/Placeholder Settings/Placeholder Settings Site Setup
DB: master
SharedFields:
- ID: "06d2c562-9229-4779-8807-e2a5fd2990d4"
  Hint: IsSystemModule
  Type: Checkbox
  Value: 1
- ID: "11488836-d40f-40d4-beb4-1d31da7b1470"
  Hint: IncludeByDefault
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Placeholder Settings Site Setup
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160713T103149Z
    - ID: "c202067e-7fab-4606-afb4-e76df2185ddc"
      Hint: Name
      Value: Placeholder Settings
