---
ID: "3e739e69-859c-4694-8d14-2ba6ca779cc6"
Parent: "dad74961-1a72-490f-a0e6-d501635f0a79"
Template: "8517dbe7-68bc-4700-ad41-379c4ebb76a0"
Path: /sitecore/templates/Branches/Foundation/Experience Accelerator/Scaffolding/Site/$name/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160624T111354Z
