---
ID: "36dc1b09-66c9-4820-b59e-901666cc113e"
Parent: "f36e70f3-122c-4847-afd4-bd8ee08722b5"
Template: "cd618631-e4e3-4943-a3a4-d3b4b39df327"
Path: /sitecore/templates/Branches/Feature/Experience Accelerator/Search/SearchDataFolder/$name/Sort Results/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160830T122325Z
    - ID: "29ac186d-0a90-470f-93d0-f548179b1fc3"
      Hint: Title
      Value: Default
