---
ID: "451aec86-2edb-45cb-81a3-8af4bbf4e7f0"
Parent: "7ea08f55-2b1d-4992-921f-703011439239"
Template: "66882e97-c8aa-4e37-8901-7a8aa35ed2ed"
Path: /sitecore/system/Workflows/Segment/Initializing/Deploy/Copy new segment into System Dimension
DB: master
SharedFields:
- ID: "a291a22b-99e2-46bb-a27b-8ec744275396"
  Hint: Type
  Value: Sitecore.ExperienceAnalytics.Aggregation.Workflows.CopySegmentAction, Sitecore.ExperienceAnalytics.Aggregation
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190702T085942Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d1d502bd-d4b9-4be7-8b8d-198930268b21"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190703T054111Z
