---
ID: "6868b051-6208-4f56-918b-cd02e5ce5c43"
Parent: "30038eef-ca75-4cca-84c3-ffb1f3a19f21"
Template: "271f5cf1-95c7-474d-9f04-06c6ebb20d8f"
Path: /sitecore/system/Settings/Rules/Definitions/Elements/Visitor/Visibility/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120807T152400
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "664ceceb-0446-4063-92a3-1e14837f4d0c"
      Hint: Rule
      Type: Rules
      Value: |
        <ruleset>
          <rule
            uid="{E8E788A7-195C-46A5-96EF-CB10F7C66BB1}">
            <conditions>
              <condition
                id="{511843B5-62DE-46AB-86C5-002F017D053C}"
                uid="CE3753515A8F4CAF853E75F1B87C496A"
                except="true" />
            </conditions>
            <actions>
              <action
                id="{EDDE9129-8CF8-4630-A625-56BA8E38489E}"
                uid="48B4910E821A4253A530AEFF77F41F43" />
            </actions>
          </rule>
        </ruleset>
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f0a09a89-11c9-49eb-8c83-d45cd41d656a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: "20150611T073329:635696048090118664Z"
    - ID: "f9abbe04-6a99-49da-906d-8b0a709c377f"
      Hint: Name
      Value: GeoIP visibility
