---
ID: "c4658673-5d70-44ed-9004-d66eac1dc718"
Parent: "a81e45db-d1f2-4946-bbaa-807edab3fd33"
Template: "bed31d6f-d968-45a9-b54e-12d7f977d861"
Path: /sitecore/system/Settings/Foundation/JSS Experience Accelerator/PlaceholderSettings/Placeholder Settings Site Setup
DB: master
SharedFields:
- ID: "06d2c562-9229-4779-8807-e2a5fd2990d4"
  Hint: IsSystemModule
  Type: Checkbox
  Value: 1
- ID: "11488836-d40f-40d4-beb4-1d31da7b1470"
  Hint: IncludeByDefault
  Type: Checkbox
  Value: 1
- ID: "40deee2f-7595-40bd-b2c9-51f9e2346100"
  Hint: Dependencies
  Type: Treelist
  Value: "{6E4A4F22-42D8-415A-9D17-80272777D6EB}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181122T001106Z
    - ID: "c202067e-7fab-4606-afb4-e76df2185ddc"
      Hint: Name
      Value: Placeholder Settings
