---
ID: "2cac1300-09fa-4c23-8a02-271c5970c134"
Parent: "80ef4164-f154-4e7d-9922-b3cfc8d74ddc"
Template: "dd22f1b3-bd87-4db2-9e7d-f7a496888d43"
Path: "/sitecore/system/Modules/PowerShell/Script Library/SXA/SXA - Scaffolding/Functions/Cmdlets/MultisiteContext/Get-SettingsItem"
DB: master
SharedFields:
- ID: "b1a94ff0-6897-47c0-9c51-aa6acb80b1f0"
  Hint: Script
  Value: |
    function Get-SettingsItem {
    	[CmdletBinding()]
        param(
    	    [Parameter(Mandatory=$true, Position=0 )]
    		[Item]$CurrentItem
        )
    
    	begin {
    		Write-Verbose "Cmdlet Get-SettingsItem - Begin"
    	}
    
    	process {
    		Write-Verbose "Cmdlet Get-SettingsItem - Process"
            $instance = [Sitecore.DependencyInjection.ServiceLocator]::ServiceProvider
            $instance.GetType().GetMethod('GetService').Invoke($instance, [Sitecore.XA.Foundation.Multisite.IMultisiteContext]).GetSettingsItem($CurrentItem) | ? { $_ -ne $null} | Wrap-Item
    	}
    
    	end {
    		Write-Verbose "Cmdlet Get-SettingsItem - End"
    	}
    }
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160711T140926Z
