---
ID: "5e9f6699-e8ed-474b-8626-2ca2934fb1a8"
Parent: "962d1760-f973-44b8-b553-8a74bcdc23fa"
Template: "962d1760-f973-44b8-b553-8a74bcdc23fa"
Path: /sitecore/templates/Foundation/Experience Accelerator/Scriban/Rule/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190521T150634Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
