---
ID: "b90549b5-c997-4d6b-b102-c9ab82528974"
Parent: "2584f622-c2d4-43e2-a5b4-0f53af0985e7"
Template: "35e75c72-4985-4e09-88c3-0eac6cd1e64f"
Path: /sitecore/templates/Branches/Foundation/Experience Accelerator/Scaffolding/Site
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160701T114836Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
