---
ID: "4caf9f9f-30c7-4117-86a4-1724971d5d2c"
Parent: "b575090a-38db-4d7d-bde5-e2b3d317e6ab"
Template: "e360bed5-b72b-4c02-890f-e434486de3f1"
Path: /sitecore/system/Modules/Experience Explorer/Components/ExpViewer/Onsite Behavior/Profiles
DB: master
SharedFields:
- ID: "64461e27-1c6a-4aa2-bda8-44e5316ef09e"
  Hint: Method
  Value: GetViewerOnsiteBehaviourProfiles
- ID: "ad8d5f6d-d0a3-4f86-a4e7-c29ff7427597"
  Hint: Path
  Value: /sitecore modules/Web/ExperienceExplorer/Controls/OnsiteBehaviour/ProfileCards/ProfileCardsViewer.ascx
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 50
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20130401T223921
    - ID: "804e29ad-9cff-4d31-b4d4-b5a6daed990b"
      Hint: Tab Name
      Value: Profiles
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "db26815b-5bb7-476b-a902-183d048280e4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: "20130911T102337:635144918175141354"
