---
ID: "60f9d721-1684-4604-a42d-ea777bc8c026"
Parent: "ae5d1384-bb75-4c6b-a8b5-4b008c2ac5da"
Template: "3aea335c-d06d-45b1-841a-cbc8d2d1ce40"
Path: /sitecore/system/Settings/Foundation/JSS Experience Accelerator/Multisite/Multisite Site Setup/Add Shared Sites Settings Item
DB: master
SharedFields:
- ID: "52c91c75-6698-4701-a8a2-242ace59a8d6"
  Hint: Location
  Type: Treelist
  Value: "{9AF6CE61-4FC5-43EE-9014-03E9D9C9C3DF}"
- ID: "7868e6bc-525c-4fce-ab8a-77da3e09b171"
  Hint: Name
  Value: Shared Sites Settings
- ID: "e62c28f0-9d3b-46e2-8bec-a5e120542499"
  Hint: Template
  Type: Treelist
  Value: "{C14BF746-030F-4E59-8594-395F6D299E61}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190211T135552Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
