---
ID: "cea3aefa-850f-4fb9-bbdc-ba5873ddf3a3"
Parent: "f07cbe89-73ae-4de6-9217-2570260cac6e"
Template: "f07cbe89-73ae-4de6-9217-2570260cac6e"
Path: /sitecore/templates/Feature/Experience Accelerator/Page Content/Promo Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {324733CF-AFEC-4281-9A18-03B6CFC4E535}
    {F07CBE89-73AE-4DE6-9217-2570260CAC6E}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
