---
ID: "02f957dc-b0a8-48ea-a532-904488b83100"
Parent: "f3f0cb13-b505-42de-9649-4a9866a0b1a7"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Foundation/Experience Accelerator/Multisite/Base/_Shared Root/Configuration
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210423T123359Z
