---
ID: "4f0d3a24-a5f2-4a35-8ed2-8b30a465c8b9"
Parent: "b74a26ad-7019-4794-ab8e-ee7c69277429"
Template: "d829066a-f9d9-4507-a922-a3f6058dbb73"
Path: /sitecore/templates/Branches/Feature/Experience Accelerator/Search/SearchDataFolder/$name/Facet Summary/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190516T114817Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
