---
ID: "a37da628-982e-415d-8645-feb67ca7263f"
Parent: "6d8ff35b-49fa-4896-b370-eb35d6b99f3f"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Foundation/Experience Accelerator/Multisite/Base/_Base Settings/Site Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181113T131910Z
