---
ID: "7e2f7e2b-9313-4b71-aba6-9401bd70b24a"
Parent: "cf309bd7-ee93-47b6-a5ba-78d2dec8f548"
Template: "cf309bd7-ee93-47b6-a5ba-78d2dec8f548"
Path: /sitecore/templates/Feature/Experience Accelerator/Media/Rendering Parameters/ImageParametersTemplate/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120619T150758
