---
ID: "9bf31f79-c337-4433-9f75-dfdca6ad5d44"
Parent: "a2c4b25d-6fab-459c-8cee-3a3320f1bee6"
Template: "a2c4b25d-6fab-459c-8cee-3a3320f1bee6"
Path: /sitecore/templates/Feature/Experience Accelerator/Security/Rendering Parameters/Social Login Wrapper/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20130722T160104
