---
ID: "c3d47557-4354-4a0f-9b5c-c60964a135e1"
Parent: "35c1b8ba-9b58-4c90-8a0d-db26eab2d928"
Template: "dd22f1b3-bd87-4db2-9e7d-f7a496888d43"
Path: "/sitecore/system/Modules/PowerShell/Script Library/SXA/SXA - Site Manager/Functions/Get-EnvironmentSites"
DB: master
SharedFields:
- ID: "b1a94ff0-6897-47c0-9c51-aa6acb80b1f0"
  Hint: Script
  Value: |
    function Get-EnvironmentSites {
    	[CmdletBinding()]
    	param(
    		[Parameter(Mandatory = $true,Position = 0)]
    		[string]$environment
    	)
    
    	begin {
    		Import-Function Get-EnvironmentSitesResolver
    		Write-Verbose "Cmdlet Get-EnvironmentSites - Begin"
    	}
    
    	process {
    		Write-Verbose "Cmdlet Get-EnvironmentSites - Process"
    
    		$environmentSitesResolver = Get-EnvironmentSitesResolver
    		$db = Get-Database -Name "master"
    
    		$allSites = $environmentSitesResolver.ResolveAllSites($db)
    		$outSites = $environmentSitesResolver.ResolveEnvironmentSites($allSites,$environment)
    		return $outSites
    	}
    
    	end {
    		Write-Verbose "Cmdlet Get-EnvironmentSites - End"
    	}
    } 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170523T153722Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
