---
ID: "55008a42-6993-4380-8320-3a0399a93a26"
Parent: "35c1b8ba-9b58-4c90-8a0d-db26eab2d928"
Template: "dd22f1b3-bd87-4db2-9e7d-f7a496888d43"
Path: "/sitecore/system/Modules/PowerShell/Script Library/SXA/SXA - Site Manager/Functions/Get-EnvironmentSitesResolver"
DB: master
SharedFields:
- ID: "b1a94ff0-6897-47c0-9c51-aa6acb80b1f0"
  Hint: Script
  Value: |
    function Get-EnvironmentSitesResolver {
    	[CmdletBinding()]
    	param()
    
    	begin {
    		Write-Verbose "Cmdlet Get-EnvironmentSitesResolver - Begin"
    	}
    
    	process {
    		Write-Verbose "Cmdlet Get-EnvironmentSitesResolver - Process"
    		
    		$instance = [Sitecore.DependencyInjection.ServiceLocator]::ServiceProvider
    		$environmentSitesResolver = $instance.GetType().GetMethod('GetService').Invoke($instance, [Sitecore.XA.Foundation.Multisite.SiteResolvers.IEnvironmentSitesResolver])
    		return $environmentSitesResolver
    	}
    
    	end {
    		Write-Verbose "Cmdlet Get-EnvironmentSitesResolver - End"
    	}
    }
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170523T153722Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
