---
ID: "673bf4d3-e284-4782-a151-66f81d6923f5"
Parent: "3784b98a-2b3a-48cf-bdbe-8aeb702ee4fc"
Template: "dd22f1b3-bd87-4db2-9e7d-f7a496888d43"
Path: "/sitecore/system/Modules/PowerShell/Script Library/SXA/SXA - Upgrade/Functions/Cmdlets/Upgrade/Dialog/Get-DialogDefaultValues"
DB: master
SharedFields:
- ID: "b1a94ff0-6897-47c0-9c51-aa6acb80b1f0"
  Hint: Script
  Value: |
    function Get-DialogDefaultValues {
    	[CmdletBinding()]
        param(
    	    [Parameter(Mandatory=$true, Position=0 )]
    		[Sitecore.XA.Foundation.Upgrade.Model.UpgradeStepInfo]$migrationInfo
        )
    
    	begin {
    		Write-Verbose "Cmdlet Get-DialogDefaultValues - Begin"
    	}
    
    	process {
    		Write-Verbose "Cmdlet Get-DialogDefaultValues - Process"
    
            $migrationInfo.DialogParameters.Insert(0, @{ Name = "Description"; Title=[Sitecore.Globalization.Translate]::Text([Sitecore.XA.Foundation.Upgrade.Texts]::Description); Value=$migrationInfo.Description; editor="info";})
            if ($migrationInfo.DryRunSupported -eq $true) {
                $migrationInfo.DialogParameters.Insert(1, @{ Name = "DryRun"; Title=[Sitecore.Globalization.Translate]::Text([Sitecore.XA.Foundation.Upgrade.Texts]::DryRunNoChangesWillBePerformed); Value=$false })
            }
    
            # map dialog values to DialogParameters
            foreach($p in $migrationInfo.DialogParameters){
                $key = $p.Name
                $value = ($migrationInfo.DialogParameters | Where-Object { $_.Name -eq $key } | Select-Object -First 1).Value
                $migrationInfo.SetDialogParameter($key, $value)
            }
    
            if ($migrationInfo.DryRunSupported -eq $true) {
                $migrationInfo.SetDialogParameter("DryRun", $DryRun)
            }
            $migrationInfo
    	}
    
    	end {
    		Write-Verbose "Cmdlet Get-DialogDefaultValues - End"
    	}
    }
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170112T140731Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
