---
ID: "c8d760a2-7ca9-405c-8869-cc1bd221cc28"
Parent: "2f6fb150-d8d8-4d62-bcae-9e58a71145bd"
Template: "e360bed5-b72b-4c02-890f-e434486de3f1"
Path: /sitecore/system/Modules/Experience Explorer/Components/ExpEditor/Onsite Behavior/Profiles
DB: master
SharedFields:
- ID: "64461e27-1c6a-4aa2-bda8-44e5316ef09e"
  Hint: Method
  Value: GetEditorOnsiteBehaviourProfiles
- ID: "ad8d5f6d-d0a3-4f86-a4e7-c29ff7427597"
  Hint: Path
  Value: /sitecore modules/Web/ExperienceExplorer/Controls/OnsiteBehaviour/ProfileCards/ProfileCardsEditor.ascx
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 50
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20130401T223921
    - ID: "804e29ad-9cff-4d31-b4d4-b5a6daed990b"
      Hint: Tab Name
      Value: Profiles
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "eb8011cc-ccaa-4895-8a49-c5c3a81b081d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: "20130902T155454:635137340944109482"
