---
ID: "3a4ff6c3-58d8-4f5c-8051-274e92d84850"
Parent: "94934361-27ec-495f-bb92-ce0d83fa181e"
Template: "94934361-27ec-495f-bb92-ce0d83fa181e"
Path: /sitecore/templates/Feature/Experience Accelerator/Sitecore Forms/Rendering Parameters/SitecoreFormWrapperParametersTemplate/__Standard Values
DB: master
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170822T070051Z
