---
ID: "042080a2-b3a7-4bf7-adb6-06c012d119b4"
Parent: "e52ab5ad-3202-4b6f-9bad-80b049c403ea"
Template: "dd91460c-d205-4d4b-8f87-d7980c8ba9f6"
Path: /sitecore/system/Settings/Forms/Meta Data/Address Book/Senders/default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201022T065222Z
    - ID: "49dc3ff7-c17d-4574-b88e-2418dce1315f"
      Hint: Value
      Value: default@domain.com
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e3715380-c235-4c22-b7cf-d2e43b9eb281"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20201105T101423Z
