---
ID: "a6906a3e-94d9-49e6-aab0-ef72c075e56b"
Parent: "9817b525-4617-4dd0-878f-270bc85bb814"
Template: "3505f93a-1bbd-4ea4-bfab-09f44e88a594"
Path: /sitecore/system/Settings/Analytics/Marketing Automation/Activity Types/Validate email address/Paths/Default
DB: master
SharedFields:
- ID: "ec7ee750-6c26-4def-aa5f-71dcd3a875de"
  Hint: Key
  Value: default
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "229cea16-4ad6-495a-aa42-0e0e05709162"
      Hint: Name
      Value: Default
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170328T130251Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "759f1061-cad8-4967-ade7-9d310df8dbc4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20170328T130302Z
