---
ID: "37a66b41-18c9-45c8-815a-c7eb4cbde83f"
Parent: "f12bdc94-438e-4ff2-ae41-4f10ebf88504"
Template: "5205cd92-0242-45aa-bead-b5c6288f2138"
Path: "/sitecore/system/Modules/PowerShell/Script Library/SXA/SXA - Upgrade/Functions/Upgrade Scripts/Add Shared Sites Settings"
DB: master
SharedFields:
- ID: "67223412-5752-426f-940f-f2f40df561f2"
  Hint: TargetVersion
  Value: 1405
- ID: "b1a94ff0-6897-47c0-9c51-aa6acb80b1f0"
  Hint: Script
  Value: |
    Import-Function Get-SiteItem
    Import-Function Invoke-AddItem
    Import-Function Get-AllSxaSite
    Import-Function Get-SettingsItem
    
    function Get-AffectedSite {
        Get-AllSxaSite | ? {
            $settingsItem = Get-SettingsItem $_        
            -not (Test-Path "$($settingsItem.Paths.Path)/Shared Sites Settings")
        }
    }
    
    function ShouldRun () {
        $items = Get-AffectedSite
        $items.Count -gt 0
    }
    
    function Get-DialogParameters () {
    }
    
    function Invoke-UpgradeStep {
        [CmdletBinding(SupportsShouldProcess = $true)]
        param(
            [Parameter(Mandatory = $true, Position = 0)]
            $arguments
        )
    
        process {
            $result = New-Object Sitecore.XA.Foundation.Upgrade.Model.UpgradeStepResult
            try {
                $actionItemId = "{4A3663EE-AC7B-4B6A-A009-3B768039A7EB}"
                $action = Get-Item -Path master: -Id $actionItemId
    
                $sites = Get-AffectedSite
                Write-Verbose "Found $($sites.Count) sites for processing.."
                foreach ($site in $sites) {
                    $path = $($site.Paths.Path)
                    if ($pscmdlet.ShouldProcess($path, "Add Shared sites settings item for site")) {
                        Invoke-AddItem $site $action
                    }
                }
    
                $result.Result = "Success"
            }
            catch {
                $result.Result = "Error"
                $result.Message = $Error[0]
                $result.ErrorObject = $Error[0]
            }
            finally {
                $result
            }
        }
    }
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 1405
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170203T091206Z
    - ID: "6ed03045-4adb-40e9-9b88-19282b6e5c90"
      Hint: Title
      Value: Support Shared sites feature
    - ID: "82563bd5-de9b-4741-b79a-9bc9163e2086"
      Hint: Description
      Value: Add settings items for SXA Shared sites feature
