---
ID: "b7ae649e-f17a-4e02-aa60-7afc1dba5e9c"
Parent: "1f46a282-d9a4-44cb-9ebb-43e0eacc5e89"
Template: "0437fee2-44c9-46a6-abe9-28858d9fee8c"
Path: /sitecore/templates/Foundation/Experience Accelerator/Local Datasources/Base
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190404T094738Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
