---
ID: "f6186688-a399-40da-9e49-aed0db96a9d7"
Parent: "90473637-7cf5-4c5f-8f9b-5043ddc0ed9f"
Template: "2e1d7985-0bf1-469b-a00b-4f2ac443940c"
Path: /sitecore/templates/Branches/Feature/Experience Accelerator/Layout Service/Layout Service Variants/$name/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170424T091812Z
