---
ID: "2ed74890-d8c9-49f1-983a-480b47de92d3"
Parent: "dcb42a80-68c9-46f9-b036-bc44a27d96fe"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Feature/Experience Accelerator/Security/Security/Base/_Role Domain/Security
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 999999
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170404T121231Z
