---
ID: "e34599a1-8e11-42ff-be90-6424a8c21ada"
Parent: "299cdb15-4745-448a-8078-68d401248eaa"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Foundation/Experience Accelerator/Scaffolding/Actions/Base/AddItem/_Name/Action
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181113T070133Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
