---
ID: "3b1f95f0-2761-4787-8c50-d52298ac8032"
Parent: "a7837de9-3266-46cb-a945-62c55da45e9e"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Foundation/Experience Accelerator/Local Datasources/Global Datasource Behavior/Datasource configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171127T140716Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
