---
ID: "fbb33ad5-2fbd-41ab-b261-1eaccd50f52f"
Parent: "7f21f14d-096b-4f27-bbcc-f115c6e6f6f1"
Template: "7f21f14d-096b-4f27-bbcc-f115c6e6f6f1"
Path: /sitecore/templates/Feature/Experience Accelerator/Page Content/Rendering Parameters/Promo/__Standard Values
DB: master
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120629T104300
