---
ID: "ef7cc826-7894-40c5-aa74-b15f36de1eb8"
Parent: "70ea3f01-0804-4a06-85aa-9dcf18ee4fb2"
Template: "d2923fee-da4e-49be-830c-e27764dfa269"
Path: /sitecore/system/Settings/Foundation/Experience Accelerator/Rendering Variants/Enums/Self Closing Tags/param
DB: master
SharedFields:
- ID: "f917c951-1f75-4d62-b14a-bc6888d7eeca"
  Hint: Value
  Value: param
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171117T133339Z
