---
ID: "3a1f68c1-1812-4f8c-94da-015b1d33e8f3"
Parent: "8f9355f1-f6ac-49a1-8465-0b905e3e8caf"
Template: "a7d9fcbc-c894-4274-935f-9b9659c000d3"
Path: "/sitecore/system/Settings/Feature/Experience Accelerator/Error Handling/Error Handling Tenant Setup/Error Handling - Settings"
DB: master
SharedFields:
- ID: "5a6ebf0f-5975-486c-807f-adff943bba13"
  Hint: Template
  Type: Treelist
  Value: "{6A8A971B-01BC-4749-9EF5-10C69BBA73FE}"
- ID: "614f52cf-d54b-47d1-a242-d9a7d42860f4"
  Hint: EditType
  Value: AddBaseTemplate
- ID: "e830af53-210b-4981-b6a8-f8939f587eb1"
  Hint: Arguments
  Type: Treelist
  Value: "{CBC14160-BED0-4AA2-9387-4C13179205B9}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170324T144733Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
