---
ID: "25fd2196-0130-49b8-8e51-079fa5032143"
Parent: "1c82e550-ebcd-4e5d-8abd-d50d0809541e"
Template: "1c82e550-ebcd-4e5d-8abd-d50d0809541e"
Path: /sitecore/templates/Foundation/Experience Accelerator/Local Datasources/Page Data/__Standard Values
DB: master
SharedFields:
- ID: "39c4902e-9960-4469-aeef-e878e9c8218f"
  Hint: __Hidden
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160616T081147Z
