---
ID: "0cb2307d-87a5-4ada-8769-49ed8703b13e"
Parent: "32359a5e-2456-4248-88ce-f3dcfabb1ff3"
Template: "ea8a3f26-9ccd-443a-95f5-71b868a94bd0"
Path: /sitecore/system/Settings/Foundation/Experience Accelerator/Placeholder Settings/Placeholder Settings Site Setup/Add Placeholder Settings Folder
DB: master
SharedFields:
- ID: "4795a7c6-08a9-4248-86c3-d460062c3a22"
  Hint: Location
  Type: Treelist
  Value: "{BEB8ED43-7243-435E-B64B-6B8B31610AFA}"
- ID: "7868e6bc-525c-4fce-ab8a-77da3e09b171"
  Hint: Name
  Value: Placeholder Settings
- ID: "e62c28f0-9d3b-46e2-8bec-a5e120542499"
  Hint: Template
  Type: Treelist
  Value: "{0339BAC0-78C1-43C1-B930-F8C26A5FDF80}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160701T083006Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
