---
ID: "cad78189-1a94-4a78-aaa0-eeece0e07447"
Parent: "cd5c935c-1f60-4d89-9a6b-88ce28305cf2"
Template: "cd5c935c-1f60-4d89-9a6b-88ce28305cf2"
Path: /sitecore/templates/Feature/Experience Accelerator/Search/Rendering Parameters/Facet Summary/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190516T133553Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
