---
ID: "9b358aea-99dc-4348-8e43-fa39b1d380cc"
Parent: "5e680478-0705-4452-a14b-42b945eb1ab6"
Template: "5e680478-0705-4452-a14b-42b945eb1ab6"
Path: /sitecore/templates/Feature/Experience Accelerator/Page Content/Rendering Parameters/IPagination/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150508T130448Z
