---
ID: "7107dc13-70d5-474c-840d-fda2f8ffe5a2"
Parent: "8df1eb92-ab86-436d-8644-36fdea56eaf6"
Template: "803949f2-13a1-4731-a0fa-e435ea0d822e"
Path: /sitecore/system/Marketing Control Panel/Taxonomies/Marketing categories/Email types/Product Updates
DB: master
Languages:
- Language: en
  Fields:
  - ID: "870a6b2a-4cac-490b-8791-195b1fc464e5"
    Hint: Description
    Value: I want to stay informed about Sitecore's latest products, features, and updates. Please send me these announcements.
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180322T110106Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f0adec28-0dfb-4b46-9758-330eed9e3da8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20180323T124518Z
