---
ID: "76e1ccd6-e469-471f-9ca9-e3cef09cd492"
Parent: "30d2d0bd-eaa7-4517-a076-94ad9d78a92a"
Template: "c4354a50-7a46-4df0-89ab-dd02db6d15cb"
Path: /sitecore/templates/Branches/Feature/Experience Accelerator/Search/SearchDataFolder/$name/Page Selector/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160606T090437Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
