---
ID: "d7856572-afc2-4cb8-84a1-d4cad015545d"
Parent: "043c849e-89f9-4f5c-a336-066d5b15754f"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/templates/Branches/Feature/Experience Accelerator/Media/Default Image Variant/$name/Default
DB: master
SharedFields:
- ID: "087c0553-9162-41f5-98d3-87eb0d80edbb"
  Hint: Compatible Renderings
  Type: TreelistEx
  Value: 
- ID: "90294353-706a-431c-b855-cd245824d9fa"
  Hint: LinkField
  Value: TargetUrl
- ID: "e1d5adba-8348-4127-9bb6-455936653839"
  Hint: CssClass
  Value: "file-type-icon-media-link"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160520T094829Z
