---
ID: "338e4dcd-1f71-45bd-b32e-4600d1a3527c"
Parent: "8807c9d3-406d-419a-9262-d8f3eae6832c"
Template: "8807c9d3-406d-419a-9262-d8f3eae6832c"
Path: /sitecore/templates/Feature/Experience Accelerator/Security/Rendering Parameters/Login/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20130320T145742
