---
ID: "34c45834-841e-4a90-8ab6-cc3761ca429a"
Parent: "592e2cc0-e0c8-4fa7-ae7d-c8ddc1d37afe"
Template: "a7d9fcbc-c894-4274-935f-9b9659c000d3"
Path: /sitecore/system/Settings/Foundation/Experience Accelerator/MVC/MVC Tenant Setup/Add MVC Site Settings Base Template
DB: master
SharedFields:
- ID: "5a6ebf0f-5975-486c-807f-adff943bba13"
  Hint: Template
  Type: Treelist
  Value: "{6A8A971B-01BC-4749-9EF5-10C69BBA73FE}"
- ID: "614f52cf-d54b-47d1-a242-d9a7d42860f4"
  Hint: EditType
  Value: AddBaseTemplate
- ID: "e830af53-210b-4981-b6a8-f8939f587eb1"
  Hint: Arguments
  Type: Treelist
  Value: "{46B0CB86-9B0F-4650-A06A-2E1CAC0F2ADC}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180702T124853Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
