---
ID: "98b8e2ce-f88f-4879-a8ca-12552cb43af1"
Parent: "38a7183c-d39c-4cea-9452-7acc54d053a2"
Template: "ea8a3f26-9ccd-443a-95f5-71b868a94bd0"
Path: /sitecore/system/Settings/Foundation/Experience Accelerator/Local Datasources/Local Datasources Site Setup/Add Datasource Configurations
DB: master
SharedFields:
- ID: "4795a7c6-08a9-4248-86c3-d460062c3a22"
  Hint: Location
  Type: Treelist
  Value: "{6A8A971B-01BC-4749-9EF5-10C69BBA73FE}"
- ID: "7868e6bc-525c-4fce-ab8a-77da3e09b171"
  Hint: Name
  Value: Datasource Configurations
- ID: "e62c28f0-9d3b-46e2-8bec-a5e120542499"
  Hint: Template
  Type: Treelist
  Value: "{F86FE270-00A4-492F-BFAF-5BF27E40CE13}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160818T084453Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
